using System;
using MigraDoc.DocumentObjectModel;
using WorkProject.Contracts.Dtos;

namespace WorkProject.Infrastructure.Export
{
    internal static class PdfCoverBuilder
    {
        public static void Build(Section section, ProjectDto project, string generatedBy)
        {
            var title = section.AddParagraph(project.Name);
            title.Format.Font.Size = 24;
            title.Format.Font.Bold = true;
            title.Format.SpaceAfter = "0.5cm";

            var sub = section.AddParagraph($"Project Status: {project.Status}");
            sub.Format.Font.Size = 12;
            sub.Format.SpaceAfter = "0.3cm";

            var dates = section.AddParagraph(
                $"Period: {project.StartDate:yyyy-MM-dd} to {project.EndDate:yyyy-MM-dd}");
            dates.Format.Font.Size = 11;
            dates.Format.SpaceAfter = "0.2cm";

            var owner = section.AddParagraph($"Owner: {project.OwnerDisplayName}");
            owner.Format.Font.Size = 11;
            owner.Format.SpaceAfter = "0.2cm";

            if (!string.IsNullOrWhiteSpace(project.Description))
            {
                section.AddParagraph().Format.SpaceBefore = "0.3cm";
                var desc = section.AddParagraph(project.Description);
                desc.Format.Font.Size = 10;
            }

            section.AddParagraph().Format.SpaceBefore = "0.5cm";
            var foot = section.AddParagraph(
                $"Generated by {generatedBy} at {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
            foot.Format.Font.Size = 9;
            foot.Format.Font.Italic = true;
        }
    }
}
